version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=pagarme
    ports:
      - 3002:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data